name: build & push Docker Image to Docker Hub

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:

  if_merged:
    if: github.event.pull_request.merged == True
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}
